name=input("enter your name:")
age=input("Enter your age:")
dob=input("Enter your DOB:")
location=input("Enter your location:")
college_name=input("Enter your college name")
print("Hello,my name is",name,"i am",age,"years old and was born on",dob,"Currently,I am located in",location,"and I completed my degree at",college_name)