print("Please Enter the following information.So,I can sell it for a profit!")
name=input("First name:")
last=input("Last name:")
grade=input("Grade(9-12):")
id=input("Student Id:")
login=input("Login:")
cgpa=input("CGPA(0.0-4.0):")
print("\nYour information:")
print("\t Login:",login)
print("\t ID:",id)
print("\t Name:",name+last)
print("\t CGPA:",cgpa)
print("\t Grade:",grade)
